version: "2.1"
services:

  db:
    restart: unless-stopped
    image: mysql:latest
    command:
     - --default_authentication_plugin=mysql_native_password
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskshop
       
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1024M
      MEMORY_LIMIT: 1024M
    links:
      - db

  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

  esearch:
    image: elasticsearch:7.5.0
    restart: unless-stopped
    environment:
      discovery.type: single-node
    volumes:
      - esearch-data:/usr/share/elasticsearch/data

  web:
    build: .
    depends_on:
      - db
      - redis
      - esearch
      - phpmyadmin
    ports:
      - "5000:5000"
    environment:
      DB_URI: mysql+pymysql://root:root@db:3306/flaskshop?charset=utf8mb4
      REDIS_URI: redis://redis:6379
      ESEARCH_URI: esearch
    restart: unless-stopped
    volumes:
    - ./:/app
    - node-modules:/app/node_modules
    

volumes:
  db_data:
  redis-data:
  esearch-data:
  node-modules:
